configuration: 
  fusion_dir: '/home/nmonnier/Data/JWST/NGC_7023/Fusion/'  # Main Fusion directory, containt all sub-directories
  data_dir: 'Corrected_slices/'  # directory containing the corrected/Filtered slice data
  result_dir: 'Results/'  # directory to save the results
  psf_dir: 'PSF/'  # directory containing the PSF data
  mrs_psf_file : 'psfs_pixscale0.1_npix_125_chan_1ABC_2ABC_3ABC_4ABC.npy'
  template_dir: 'Templates/'  # directory containing the spectral templates
  templates_file: 'pca_NGC7023_1ABC_2ABC_3ABC_4AB_16_templates.npy'  # spectral templates file
  wavelength_file: 'wavel_axis_NGC7023_1ABC_2ABC_3ABC_4AB.npy'  # wavelength axis file
  reference_wavelength_file: 'wavel_axis_NGC7023_1ABC_2ABC_3ABC_4ABC.npy'  # Wavelength axis for reference cube 
cube:
  npix : 125 # number of pixels in each spatial dimension 
  pixel_resolution: 0.1  # arcsec
reconstruction:
  method : 'lcg'  # reconstruction method: 'lcg' or 'mmmg'
  max_iter : 121  # maximum number of iterations
  mu : 5e6  # regularization parameter
MRS:
  list_channels: ['1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b']  # list of channels to use
  scale_data: True  # Convert data from Jy to Jy/str
  spectral_lines: True  # Enable spectral line processing